---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-sm-bmc-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: '{{ `{{ index . "username" }}` }}'
        password: '{{ `{{ index . "password" }}` }}'
  data:
    - secretKey: username
      remoteRef:
        key: /tink/ruffio/default-sm-bmc-auth
        property: username
    - secretKey: password
      remoteRef:
        key: /tink/ruffio/default-sm-bmc-auth
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default-dell-bmc-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: '{{ `{{ index . "username" }}` }}'
        password: '{{ `{{ index . "password" }}` }}'
  data:
    - secretKey: username
      remoteRef:
        key: /tink/ruffio/default-dell-bmc-auth
        property: username
    - secretKey: password
      remoteRef:
        key: /tink/ruffio/default-dell-bmc-auth
        property: password
