---
apiVersion: v1
kind: ConfigMap
metadata:
  name: download-image
data:
  entrypoint.sh: |-
    #!/usr/bin/env bash
    # This script is designed to download a cloud image file (.img) and then convert it to a .raw.gz file.
    # This is purpose built so non-raw cloud image files can be used with the "image2disk" action.
    # See https://artifacthub.io/packages/tbaction/tinkerbell-community/image2disk.
    set -euxo pipefail
    if ! which pigz qemu-img &>/dev/null; then
    	apk add --update pigz qemu-img
    fi
    image_url=$1
    file=$2/${image_url##*/}
    file=${file%.*}.raw.gz
    mkdir -p $2
    if [[ ! -f "$file" ]]; then
    	wget "$image_url" -O image.img
    	qemu-img convert -O raw image.img image.raw
    	pigz <image.raw >"$file"
    	rm -f image.img image.raw
    fi

{{- range $os, $releases := .Values.stack.os }}
{{- range $releases }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-{{ $os }}-{{ .name }}
spec:
  template:
    spec:
      containers:
        - name: download-{{ $os }}-{{ .name }}
          image: bash:5.2.2
          command: ["/script/entrypoint.sh"]
          args:
            [
              {{ .url | quote }},
              "/output/{{$os}}/{{ .name }}",
            ]
          volumeMounts:
            - mountPath: /output
              name: hook-artifacts
            - mountPath: /script
              name: configmap-volume
      restartPolicy: OnFailure
      volumes:
        {{- if $.Values.stack.hook.enabled }}
        {{- if $.Values.stack.hook.localDirectory }}
        - name: hook-artifacts
          hostPath:
            path: {{ $.Values.stack.hook.downloadsDest }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if $.Values.stack.hook.persistentStorage }}
        - name: hook-artifacts
          persistentVolumeClaim:
            claimName: hook-artifacts
        {{- end }}
        {{- end }}
        - name: configmap-volume
          configMap:
            defaultMode: 0700
            name: download-image
{{- end }}
{{- end }}
